### PR TITLE
UI bug issues

### LINKED ISSUE #49: Prioritize: MSW  website UI Fixes
- [x] Optimize MSW logo for landing page.

image

- [x] Background image for safari is still blank

image

- [x] Fix Footer alignment for iPad pro, iPad 8 and other similar devices.

image

- [x] Center header for iPad8, iPad pro and other similar devices.

image

- [x] On iPad pro and similar devices, when clicking on team on the header, indicator is stuck on NFT characters.

image

### PR DESCRIPTION
**Pull request by vkth**
This resolves the following issues:

Resolves #49 Optimize website assets
026406c425c5a33bec912140bbf9cb44ff1deb6c
image

Resolves #49 Adjust footer and navbar alignments for ipad
453d545642a3c98cf82071ecb1d3b6367da38dee
image

Resolves #49 First attempt to fix background video for safari
27bbbee573b5a52e0d854bd7085a514f34cffbd5

### CODE REVIEW

**Comment by Emman1598** [comment]
For Safari's Background, i downloaded a windows version, not sure if the same sa mga apple devices ang result. sakindi pa nag a-appear background. 
image

**Comment by vkth** [comment]
Same sir sakin iba-iba na din po ang lumalabas

**Comment by Emman1598** [comment]
> Same sir sakin iba-iba na din po ang lumalabas

Hmmm, lets wait for sir @swengr-janan 's review if ganun din sakanya.

**Comment by Emman1598** [comment]
For footer, its not yet fixed for iPad pro and other similar devices. @vkth 


image

**Comment by vkth** [comment]
Sir anong size po nitong ipad pro? yung dimensions niya po ? thanks

**Comment by Emman1598** [comment]
> Sir anong size po nitong ipad pro? yung dimensions niya po ? thanks

for ipad pro 1024 x 1366, for ipad 8 okay na siya.

**Comment by Emman1598** [comment]
Pa address muna po mam @vkth nung sa footer bago me mag approve hehe. Salamats!

**Review by Emman1598 — APPROVED** [review]
All goods!

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
